-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS MICROHOUSE
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- Databases
CREATE DATABASE IF NOT EXISTS MICROHOUSE_RAW;
CREATE DATABASE IF NOT EXISTS MICROHOUSE_ANALYTICS;

-- Schemas
CREATE SCHEMA IF NOT EXISTS MICROHOUSE_ANALYTICS.STAGING;
CREATE SCHEMA IF NOT EXISTS MICROHOUSE_ANALYTICS.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS MICROHOUSE_ANALYTICS.MARTS;

-- Role
CREATE ROLE IF NOT EXISTS FINHOUSE_ROLE;

-- Permissions
-- MICROHOUSE WAREHOUSE
GRANT USAGE ON WAREHOUSE MICROHOUSE TO ROLE FINHOUSE_ROLE;

-- RAW DATABASE
GRANT USAGE ON DATABASE MICROHOUSE_RAW TO ROLE FINHOUSE_ROLE;

-- Allow the role to use the schema
GRANT USAGE ON SCHEMA MICROHOUSE_RAW.PUBLIC TO ROLE FINHOUSE_ROLE;

-- Allow creating tables and views in the schema
GRANT CREATE TABLE ON SCHEMA MICROHOUSE_RAW.PUBLIC TO ROLE FINHOUSE_ROLE;
GRANT CREATE VIEW ON SCHEMA MICROHOUSE_RAW.PUBLIC TO ROLE FINHOUSE_ROLE;

GRANT USAGE ON SCHEMA MICROHOUSE_RAW.PUBLIC TO ROLE FINHOUSE_ROLE;
GRANT USAGE, READ, WRITE ON STAGE MICROHOUSE_RAW.PUBLIC.RAW_STAGE TO ROLE FINHOUSE_ROLE;

-- ANALYTICS DATABASE
-- STAGING
GRANT USAGE ON DATABASE MICROHOUSE_ANALYTICS TO ROLE FINHOUSE_ROLE;

-- Allow the role to use the schema
GRANT USAGE ON SCHEMA MICROHOUSE_ANALYTICS.STAGING TO ROLE FINHOUSE_ROLE;

-- Allow creating tables and views in the schema
GRANT CREATE TABLE ON SCHEMA MICROHOUSE_ANALYTICS.STAGING TO ROLE FINHOUSE_ROLE;
GRANT CREATE VIEW ON SCHEMA MICROHOUSE_ANALYTICS.STAGING TO ROLE FINHOUSE_ROLE;

-- INTERMEDIATE
-- Allow the role to use the schema
GRANT USAGE ON SCHEMA MICROHOUSE_ANALYTICS.INTERMEDIATE TO ROLE FINHOUSE_ROLE;

-- Allow creating tables and views in the schema
GRANT CREATE TABLE ON SCHEMA MICROHOUSE_ANALYTICS.INTERMEDIATE TO ROLE FINHOUSE_ROLE;
GRANT CREATE VIEW ON SCHEMA MICROHOUSE_ANALYTICS.INTERMEDIATE TO ROLE FINHOUSE_ROLE;

-- MARTS
-- Allow the role to use the schema
GRANT USAGE ON SCHEMA MICROHOUSE_ANALYTICS.MARTS TO ROLE FINHOUSE_ROLE;

-- Allow creating tables and views in the schema
GRANT CREATE TABLE ON SCHEMA MICROHOUSE_ANALYTICS.MARTS  TO ROLE FINHOUSE_ROLE;
GRANT CREATE VIEW ON SCHEMA MICROHOUSE_ANALYTICS.MARTS TO ROLE FINHOUSE_ROLE;

-- User
CREATE USER IF NOT EXISTS FINHOUSE_USER
  PASSWORD = 'password'
  DEFAULT_ROLE = FINHOUSE_ROLE
  DEFAULT_WAREHOUSE = MICROHOUSE;

-- SECURITYADMIN cannot grant priviledges only ACCOUNT ADMIN can
USE ROLE ACCOUNTADMIN;
GRANT ROLE FINHOUSE_ROLE TO USER FINHOUSE_USER;
GRANT ALL PRIVILEGES ON DATABASE MICROHOUSE_RAW TO ROLE FINHOUSE_ROLE;

GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE MICROHOUSE_RAW TO ROLE FINHOUSE_ROLE;

GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE MICROHOUSE_RAW TO ROLE FINHOUSE_ROLE;

GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE MICROHOUSE_RAW TO ROLE FINHOUSE_ROLE;

GRANT ALL PRIVILEGES ON DATABASE MICROHOUSE_ANALYTICS TO ROLE FINHOUSE_ROLE;

GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE MICROHOUSE_ANALYTICS TO ROLE FINHOUSE_ROLE;

GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE MICROHOUSE_ANALYTICS TO ROLE FINHOUSE_ROLE;

GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE MICROHOUSE_ANALYTICS TO ROLE FINHOUSE_ROLE;
